default: &default
    adapter: mysql2
    encoding: utf8
    host: 127.0.0.1
    username: atlas
    password: 12341234

development:
  <<: *default
  database: my_atlas

test:
  <<: *default
  database: my_atlas_test
